@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDQ5NzM4MjV9.5psn37y6DIwrLHGhkLunBLVO2HXVUVoCoYdFgMYn3Qg
#nonadmin

#Movies Index 
GET http://localhost:3000/movies

###
#Movies Create
POST http://localhost:3000/movies
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "title": "The Party",
  "year": 1968,
  "plot": "A clerical mistake results in a bumbling Indian film star being invited to an exclusive Hollywood party instead of being fired.",
  "director": "Blake Edwards",
  "english": true
}

###
#Movies Show
GET http://localhost:3000/movies/2

###
#Movies Update
PATCH http://localhost:3000/movies/20
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "title": "The Party"
}

###
#Movies Destroy
DELETE http://localhost:3000/movies/19
Authorization: Bearer {{ jwt }}

########ACTORS#########

#Actor Index
GET http://localhost:3000/actors

###
#Actor Create
POST http://localhost:3000/actors
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "first_name": "Corrie",
  "last_name": "Leech",
  "known_for": "Coding Blunders 2.0",
  "age": 35,
  "gender": "male",
  "movie_id": 20
}

###
#Actors Show
GET http://localhost:3000/actors/7

###
#Actors Update
PATCH http://localhost:3000/actors/18
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "age": 35,
  "gender": "female"
}

###
#Actors Destory
DELETE http://localhost:3000/actors/18
Authorization: Bearer {{ jwt }}

###
#Movie Genre Create
POST http://localhost:3000/movie_genres/
Content-Type: application/json

{
  "movie_id": 13,
  "genre_id": 5
}