### Users Create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Admin",
  "email": "admin@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}

###
### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "yuna@gmail.com",
  "password": "password"
}

###