#Movies Index
GET http://localhost:3000/movies

###
#Movies Create
POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "Parasite",
  "year": 2019,
  "plot": "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
  "director": "Bong Joon Ho",
  "english": false
}

###
#Movies Show
GET http://localhost:3000/movies/2

###
#Movies Update
PATCH http://localhost:3000/movies/12
Content-Type: application/json

{
  "title": "Coding Wonderland"
}

###
#Movies Destroy
DELETE http://localhost:3000/movies/14

########ACTORS#########

#Actor Index
GET http://localhost:3000/actors

###
#Actor Create
POST http://localhost:3000/actors
Content-Type: application/json

{
  "first_name": "Will",
  "last_name": "Smith",
  "known_for": "Men in Black",
  "age": 10,
  "gender": "male",
  "movie_id": 7
}

###
#Actors Show
GET http://localhost:3000/actors/7

###
#Actors Update
PATCH http://localhost:3000/actors/7
Content-Type: application/json

{
  "age": 12,
  "gender": "male"
}

###
#Actors Destory
DELETE http://localhost:3000/actors/16

###